apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ayd2-practica
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ayd2-practica
    spec:
      containers: 
        - image: davidtortola/ayd2:practica
          name: client
          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              cpu: 0.1
              memory: 256M}
      restartPolicy: Always
status: {}